version: "3.7"
services:
    # image project
    player:
        build: 
            args: 
                user: jpls
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-mp3
        container_name: php_mp3
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - mp3
    
    # nginx
    nginx:
        image: nginx:alpine
        container_name: nginx_mp3
        restart: unless-stopped
        ports: 
            - 9000:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - mp3

    # db mysql
    mysql:
        image: mysql:5.7.22
        container_name: mysql_mp3
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: player
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - 3390:3306
        networks: 
            - mp3

networks: 
    mp3:
        driver: bridge